# Site Configuration

# Theme, mapped to the directory: ./theme/xxxx
theme: default

# HTML Language setting
lang: "en"

# Plugins, implemented in ./plugins/PLUGIN_NAME
# Use {{ vars.PLUGIN_NAME }} in the settings below

# The output of the plugin can be used below, e.g., {{vars.MediumFollowersCountPlugin}}
plugins:
  # Automatically fetch Medium follower count
  #- MediumFollowersCountPlugin:
  #    username: zhgchgli
  # Automatically fetch Github repo star count
  - GithubRepoStarsCountPlugin:
      - ZhgChgLi/ZMarkupParser
      - ZhgChgLi/ZReviewTender
      - ZhgChgLi/ZMediumToMarkdown
      - ZhgChgLi/linkyee

# Google Analytics tracking id
google_analytics_id:

# HTML Title
title: "JKWMoore's Links"

# Avatar image path
avatar: "./images/profile.jpeg"

# Name section text
name: "@jkwmoore"

# Tagline section text
tagline: >-
    Senior Research Platforms Engineer at IT Services - University of Sheffield

# List of links
# icon: Use Font Awesome icons (https://fontawesome.com/search?o=r&m=free)
# text: The displayed text for the link
# title: The url title
# url: The URL of the link
# alt: Alternative text for accessibility
# target: `_blank` opens in a new tab, `_self` opens in the same frame
links:
  - link:
      icon: "fa-solid fa-blog"
      text: "Blog</span>"
      url: "https://blog.jkwmoore.dev/"
      alt: "JKWMoore's Blog"
      title: "JKWMoore's Blog"
      target: "_blank"
  - link:
      icon: "fa-solid fa-rss"
      text: "Website"
      url: "https://zhgchg.li/"
      alt: "ZhgChgLi's Website"
      title: "ZhgChgLi's Website"
      target: "_blank"


# List of social media links
# icon: Use Font Awesome icons (https://fontawesome.com/search?o=r&m=free)
# title: The url title
# url: The URL of the social media link
# alt: Alternative text for accessibility
# target: _blank opens in a new tab, _self opens in the same frame
socials:
  - social:
      icon: "fa-brands fa-github"
      url: "https://github.com/jkwmoore"
      title: "JKWMoore's GitHub"
      alt: "JKWMoore's GitHub"
      target: "_blank"
  - social:
      icon: "fa-brands fa-mastodon"
      url: "https://mast.hpc.social/@jkwmoore"
      title: "JKWMoore's Mastodon"
      alt: "JKWMoore's Mastodon"
      target: "_blank"
  - social:
      icon: "fa-brands fa-linkedin"
      url: "https://github.com/jkwmoore"
      title: "JKWMoore's LinkedIn"
      alt: "JKWMoore's LinkedIn"
      target: "_blank"

# Footer text
footer: >
    Hi there! Follow me on GitHub and Mastodon, or stay connected on LinkedIn.

# Footer copyright message
# Linkyee is a 100% free, open-source project—feel free to modify the copyright message as you like. :)
copyright: >
  © 2025  <a href="https://link.jkwmoore.dev/" target="_blank">JKWMoore</a>. Powered by <a href="https://github.com/ZhgChgLi/linkyee" target="_blank">linkyee</a>
